openapi: 3.0.3
info:
  title: Supplier Management API
  version: 1.0.0
  description: API for managing supplier profiles in the Ledger system.

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /suppliers/profile:
    post:
      summary: Create a new supplier
      operationId: createSupplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierRequestDTO'
      responses:
        '201':
          description: Supplier created successfully
          headers:
            Location:
              description: URI of the created supplier
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponseDTO'
        '400':
          description: Invalid input

    get:
      summary: Get all suppliers
      operationId: getAllSuppliers
      responses:
        '200':
          description: List of all suppliers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplierResponseDTO'

  /suppliers/profile/{uuid}:
    get:
      summary: Get a supplier by UUID
      operationId: getSupplierById
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Supplier found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponseDTO'
        '404':
          description: Supplier not found

    put:
      summary: Update an existing supplier
      operationId: updateSupplier
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierRequestDTO'
      responses:
        '200':
          description: Supplier updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponseDTO'
        '404':
          description: Supplier not found

    delete:
      summary: Delete a supplier by UUID
      operationId: deleteSupplier
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Supplier deleted successfully
        '404':
          description: Supplier not found

components:
  schemas:
    SupplierRequestDTO:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 255
          example: ACME Supplies Inc.
        address:
          type: string
          maxLength: 255
          example: 123 Elm Street, Springfield
        taxId:
          type: string
          maxLength: 255
          example: TIN-123-456-789
        diversityStatus:
          type: string
          maxLength: 255
          example: Women-Owned Business

    SupplierResponseDTO:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: ACME Supplies Inc.
        address:
          type: string
          example: 123 Elm Street, Springfield
        taxId:
          type: string
          example: TIN-123-456-789
        diversityStatus:
          type: string
          example: Women-Owned Business
        createdAt:
          type: string
          format: date-time
          example: 2025-08-08T12:34:56
